##test db
CREATE DATABASE IF NOT EXISTS `vagranttests`;

USE `vagranttests`;

CREATE TABLE IF NOT EXISTS `vtests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT 'title',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4 AUTO_INCREMENT=1 ;
